<?php
declare(strict_types=1);

namespace Html;

class UserProfileWithAvatar extends UserProfile
{
    public function toHtml(): string
    {
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}